language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  

os:
  - linux


install:
  - pip install --upgrade pip
  - pip install MakeLog
  - pip install coveralls
  - pip install coverage

script:
  - coverage run test_makelog.py
after_success:
  - coveralls