language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
  - "3.0"
  - "2.7.11"  
os:
  - linux
  
install:
  - pip install --upgrade pip
  - pip install MakeLog

script:
  - python -m unittest -v test_makelog
