language: python
python:
  - "3.6"
os:
  - linux
  
virtualenv:
  system_site_packages: true
  
install:
  - pip install --upgrade pip
  - pip install MakeLog

script:
  - python -m unittest -v test_makelog
