language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  
os:
  - linux
  - osx
  
install:
  - pip install --upgrade pip
  - pip install MakeLog

script:
  - python -m unittest -v test_makelog
  - pip install coverage
  - coverage run test_makelog.py