language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  

os:
  - linux


install:
  - pip install --upgrade pip
  - pip install MakeLog
  - pip install coveralls

script:
  - python -m unittest -v test_makelog
  - coverage run test_makelog.py
  
after success:
  - coveralls